const birdsList = [
  'bażant',
  'błotniak łąkowy',
  'błotniak stawowy',
  'cierniówka',
  'czajka',
  'sikoroka czarnogłówka',
  'sikorka czubatka',
  'dymówka',
  'dzierlatka',
  'dzięcioł czarny',
  'dzięcioł duży',
  'dzięcioł zielony',
  'dzwoniec',
  'gajówka',
  'gąsiorek',
  'gil',
  'grubodziób',
  'jerzyk',
  'kapturka',
  'kawka',
  'kląskawka',
  'kopciuszek',
  'kos',
  'kowalik',
  'krzyżówka',
  'kukułka',
  'kulczyk',
  'kuropatwa',
  'kwiczoł',
  'lerka',
  'łozówka',
  'makolągwa',
  'mazurek',
  'modraszka',
  'muchołówka żałobna',
  'mysikrólik',
  'oknówka',
  'ortolan',
  'paszkot',
  'pełzacz leśny',
  'pełzacz ogrodowy',
  'piegża',
  'pierwiosnek',
  'pleszka',
  'pliszka górska',
  'pliszka siwa',
  'pliszka żółta',
  'pokląskwa',
  'pokrzywnica',
  'potrzeszcz',
  'potrzos',
  'przepiórka',
  'pustułka',
  'raniuszek',
  'rudzik',
  'sierpówka',
  'sikora uboga',
  'sikorka bogatka',
  'sikorka modraszka',
  'skowronek',
  'słowik rdzawy',
  'słowik szary',
  'skorka sosnówka',
  'sójka',
  'sroka',
  'srokosz',
  'strumieniówka',
  'strzyżyk',
  'szczygieł',
  'szpak',
  'śpiewak',
  'świergotek drzewny',
  'świergotek łąkowy',
  'świerszczak',
  'świstunka leśna',
  'trznadel',
  'wilga',
  'wrona siwa',
  'wróbel',
  'zaganiacz',
  'zięba',
  'zniczek',
  'żuraw',
];

export default { birdsList };
